package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"

	"github.com/spf13/cobra"
)

var trustCmd = &cobra.Command{
	Use:   "trust",
	Short: "Install the Portree CA certificate into the system trust store",
	Long: `Install the Portree development CA certificate into the system trust store
so that browsers and other tools trust HTTPS certificates generated by portree.

On macOS, this uses the security command to add the certificate to the System keychain.
On Linux, this copies the certificate to /usr/local/share/ca-certificates/ and runs update-ca-certificates.

This command requires sudo/root privileges.
Run 'portree proxy start --https' first to generate the CA certificate.`,
	RunE: func(cmd *cobra.Command, args []string) error {
		caPath := filepath.Join(stateRoot, ".portree", "certs", "ca.crt")
		if _, err := os.Stat(caPath); os.IsNotExist(err) {
			return fmt.Errorf("CA certificate not found at %s\nRun 'portree proxy start --https' first to generate certificates", caPath)
		}

		switch runtime.GOOS {
		case "darwin":
			return trustDarwin(caPath)
		case "linux":
			return trustLinux(caPath)
		default:
			fmt.Printf("Automatic trust store installation is not supported on %s.\n", runtime.GOOS)
			fmt.Printf("Please manually install the CA certificate:\n  %s\n", caPath)
			return nil
		}
	},
}

func trustDarwin(caPath string) error {
	fmt.Println("Installing CA certificate into macOS System keychain...")
	fmt.Println("You may be prompted for your password.")

	c := exec.Command("sudo", "security", "add-trusted-cert",
		"-d", "-r", "trustRoot",
		"-k", "/Library/Keychains/System.keychain",
		caPath)
	c.Stdin = os.Stdin
	c.Stdout = os.Stdout
	c.Stderr = os.Stderr

	if err := c.Run(); err != nil {
		return fmt.Errorf("failed to install CA certificate: %w", err)
	}

	fmt.Println("CA certificate installed successfully.")
	return nil
}

func trustLinux(caPath string) error {
	destDir := "/usr/local/share/ca-certificates/portree"
	destPath := filepath.Join(destDir, "portree-dev-ca.crt")

	fmt.Println("Installing CA certificate into system trust store...")
	fmt.Println("You may be prompted for your password.")

	// Create destination directory.
	mkdirCmd := exec.Command("sudo", "mkdir", "-p", destDir)
	mkdirCmd.Stdin = os.Stdin
	mkdirCmd.Stdout = os.Stdout
	mkdirCmd.Stderr = os.Stderr
	if err := mkdirCmd.Run(); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", destDir, err)
	}

	// Copy CA certificate.
	cpCmd := exec.Command("sudo", "cp", caPath, destPath)
	cpCmd.Stdin = os.Stdin
	cpCmd.Stdout = os.Stdout
	cpCmd.Stderr = os.Stderr
	if err := cpCmd.Run(); err != nil {
		return fmt.Errorf("failed to copy CA certificate: %w", err)
	}

	// Update certificate store.
	updateCmd := exec.Command("sudo", "update-ca-certificates")
	updateCmd.Stdin = os.Stdin
	updateCmd.Stdout = os.Stdout
	updateCmd.Stderr = os.Stderr
	if err := updateCmd.Run(); err != nil {
		return fmt.Errorf("failed to update CA certificates: %w", err)
	}

	fmt.Println("CA certificate installed successfully.")
	return nil
}

func init() {
	rootCmd.AddCommand(trustCmd)
}
